### PR TITLE
Fix Eclipse and .gitignore mismatch

### PR DESCRIPTION
**Pull request by victornoel**
@g4s8 this has been bothering me for some time, here are a fix for using this repo properly with eclipse

### CODE REVIEW

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this pull request is too small, just 9 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @g4s8[/z](https://www.0crat.com/u/g4s8) please review this and merge or reject

**Comment by g4s8** [comment]
@victornoel thanks

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:g4s8/ghman#49` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
