### PR TITLE
(#2) Fix PDD too short descriptions.

### PR DESCRIPTION
**Pull request by samihibrahim**
Due to me using too short puzzle descriptions, PDD bot is unable to handle these puzzles. This PR is to remedy that.

### CODE REVIEW

**Comment by samihibrahim** [comment]
@g4s8 here is the updated puzzle descriptions.

**Comment by 0crat** [comment]
Job [#33](https://github.com/g4s8/ghman/issues/33) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#33](https://github.com/g4s8/ghman/issues/33) is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/cedbdc41-feb6-4df4-8ac4-5e07d22044ca); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by g4s8** [comment]
@samihibrahim thanks

**Comment by g4s8** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/g4s8/ghman/issues/33#issuecomment-502481423))

@g4s8 The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#33](https://github.com/g4s8/ghman/issues/33), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#33](https://github.com/g4s8/ghman/issues/33) is assigned to @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova), here is [why](https://www.0crat.com/footprint/CJT4R32Q3/98fa0641-a394-41ba-b8f1-4833003b9a1c); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @g4s8[/z](https://www.0crat.com/u/g4s8) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/g4s8/ghman/issues/33#issuecomment-502482686))

@g4s8 The user @olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) resigned from [#33](https://github.com/g4s8/ghman/issues/33), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Job `gh:g4s8/ghman#33` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#33](https://github.com/g4s8/ghman/issues/33) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Pull request merged**
